### ISSUE TITLE
Different message from vscode and terminal

### ISSUE THREAD

**Issue by shafarizkyf** [d9705996/vscode-tighten-lint#1]
I have installed tlint globally and tighten-lint for vscode. I setup tlint.json in the project root. But it seems the plugin not reading tlint.json, for example I prefer to disabled the SpaceAfterSoleNotOperator. my code looks something like this

`if(!$this->auth->userid()){
      return redirect('logout');
    }`

in vscode at problems tabs showing "tighten-lint: ! No parenthesis on empty instantiations (NoParensEmptyInstantiations)" but if I run via terminal there is no error which is correct that I ignore that specific rule.

I'm missing something ?

**Comment by malvinys** [comment]
i got the same problem, this is my tlint.json :
```
{
  "preset": "laravel",
  "disabled": ["AlphabeticalImports"]
}
```
and in vscode `AlphabeticalImports` still work.

**Comment by loganhenson** [comment]
The tlint cli looks at the the `cwd`, we may need to set it when running exec

https://github.com/d9705996/vscode-tighten-lint/blob/master/src/providers/LintProvider.ts#L61

**Comment by d9705996** [comment]
@loganhenson - Awesome - thanks for the pointer.  I have created a fix and will push out a new release to marketplace in a few minutes

**Comment by d9705996** [comment]
@shafarizkyf, @malvinys -  I have pushed out v0.1.0 which should fix the issue.   Please make sure the extension has updated and add your `tlint.json` to the root of you project (I've updated the docs with an example)  

Any issues please raise a new issue with details of the new problem

**Comment by malvinys** [comment]
awesome, its work. thank you
