### ISSUE TITLE
Disable a specific rule?

### ISSUE THREAD

**Issue by mobayen** [d9705996/vscode-tighten-lint#8]
Is there a way to disable a specific rule to run?
The [Linter](https://github.com/tightenco/tlint) itself has a "disabled" functionality but I can not find such a thing for the VSCode extension!

**Comment by d9705996** [comment]
You can use a [config file](https://github.com/d9705996/vscode-tighten-lint#tlintusing-a-configuration-file) to apply disabled rules.

**Comment by mobayen** [comment]
@d9705996 
There is a "tighten-lint.disable" or something like that?
I saw only "tighten-lint.only" which is not to disabled rules!

**Comment by d9705996** [comment]
You need to create a `tlint.json` file in the root of your project and add your configuration e.g.

```json
{
  "preset": "laravel",
  "disabled": ["NoInlineVarDocs"],
  "excluded": [
    "tests/"
  ]
}
```

It's not a setting within vscode. If you need this functionality as a setting I'm open to PRs
